### ISSUE TITLE
extend build system for different target architectures and settings

### ISSUE THREAD

**Issue by jevbelikov** [CAMP-benchmark/CAMP#1]
as a user I would like to build CAMP with `ARCH=archer2-gnu make` command to compile with gnu on A2 and `ARCH=archer2-cray` or `ARCH=cirrus-gnu` etc for other setups; this can also include profinling and debugging builds

I suggest to use simple if-endif clauses and string matching.

**Comment by jevbelikov** [comment]
@pvvq please check is suggested changes. It is first step, but still need to improve checking that supported ARCH value was provided.

**Comment by pvvq** [comment]
add check for invalid values in commit eaf5243

**Comment by jevbelikov** [comment]
looks good, closing the issue
